default:\
	:tc=universal-ctags@/usr/share/gtags/gtags.conf:\
	:skip=zu/src/zlib/,zm/src/zlib/,zt/src/zlib/,ze/src/zlib/,zi/src/zlib/,ztls/src/zlib/,zhttp/src/zlib/,zrest/src/zlib/,zws/src/zlib/,zfb/src/zlib/,zv/src/zlib/,zdb/src/zlib/,zdb_pq/src/zlib/,zdb_pq/ext/zlib/,zum/src/zlib/,zdf/src/zlib/,zrl/src/zlib/,zcmd/src/zlib/,zproxy/src/zlib/,zgtk/src/zlib/:
