include "zfb_types.fbs";
namespace Zum.fbs;
table Refresh {
  id:[ubyte];
  issuer:string;
  app_i_d:uint64;
  user_i_d:uint64;
  client_i_d:string;
  credential_i_d:[ubyte];
  audience:string;
  actions:Zfb.Bitmap;
  digest:[ubyte];
  spent:[Zfb.Bytes];
  auth_version:uint64;
  auth_time:int64;
  created:int64;
  expires:int64;
  generation:uint32;
  state:int8;
  owner:Zfb.UInt128;
  requested_role_i_ds:[uint64];
  role_i_ds:[uint64];
  user_version:uint64 = 1;
  client_version:uint64;
  membership_version:uint64;
  policy_version:uint64;
  evidence_version:uint64;
  authority_source:int8;
  scope:string;
  nonce:string;
  authority_provider_i_d:uint64;
  version:uint64 = 1;
  updated:int64;
}
root_type Refresh;
