include "zfb_types.fbs";
namespace Zum.fbs;
table Grant {
  id:[ubyte];
  issuer:string;
  app_i_d:uint64;
  audience_i_d:uint64;
  user_i_d:uint64;
  client_i_d:string;
  facade_client_i_d:string;
  credential_i_d:[ubyte];
  audience:string;
  redirect_u_r_i:string;
  scope_i_ds:[uint64];
  actions:Zfb.Bitmap;
  digest:[ubyte];
  spent:[Zfb.Bytes];
  challenge:[ubyte];
  binding_digest:[ubyte];
  pkce_challenge:[ubyte];
  oauth_state:string;
  auth_version:uint64;
  auth_time:int64;
  created:int64;
  expires:int64;
  generation:uint32;
  kind:int8;
  purpose:int8;
  state:int8;
  owner:Zfb.UInt128;
  user_name:string;
  user_handle:[ubyte];
  role_i_ds:[uint64];
  label:string;
  user_version:uint64 = 1;
  client_version:uint64;
  membership_version:uint64;
  policy_version:uint64;
  evidence_version:uint64;
  authority_source:int8;
  actor:string;
  oauth_state_present:bool;
  scope:string;
  nonce:string;
  authority_provider_i_d:uint64;
  prompt:string;
  max_age:uint64;
  prompt_present:bool;
  max_age_present:bool;
}
root_type Grant;
