//  -*- mode:c++; indent-tabs-mode:t; tab-width:8; c-basic-offset:2; -*-
//  vi: noet ts=8 sw=2 cino=+0,(s,l1,m1,g0,N-s,j1,U1,W2,i2

// Generated by the reference age CLI v1.3.2 with unencrypted OpenSSH keys.
// These randomly generated keys are test fixtures, not production identities.

struct ZtlsAgeSSHVector {
  const char *name;
  const char *privateKey;
  const char *publicKey;
  const char *cipher;
};

static constexpr ZtlsAgeSSHVector ZtlsAgeSSHVectors[] = {
  {"rsa",
    "-----BEGIN OPENSSH PRIVATE KEY-----\n"
    "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn\n"
    "NhAAAAAwEAAQAAAQEAjsThg3CWrV442AIA4/jD6I36fcNqf48Aj5baW4U71kEdkAGQIIgt\n"
    "li9b2RIPEwCUrIQXBETH+YujbKbV9s3X4ZqcaeAIFle8ZZ2BjkJG0TtWUgXBEQWc6SxM+L\n"
    "xD2OwCQ7D4h6dKh5AD3sKS7lwFEqeC2gYcWbXwvLzYO/ageWpn/r5X+1faw02rCxGRO5e8\n"
    "qyWdPvbCX+TnC9E3E4MwEedO2B0T8HGFrY8CVLzg+IiaIAOonhrReH53IIOtTMNXkSrqsG\n"
    "WX1NYEgoBA3jg3l8dsjwEl/rWbqIFLpDgE7Yzz0N8uzim2lHSa6Q9MwL0KE0q2k6x1cPV1\n"
    "dXorPiq6rQAAA8hgkKLoYJCi6AAAAAdzc2gtcnNhAAABAQCOxOGDcJatXjjYAgDj+MPojf\n"
    "p9w2p/jwCPltpbhTvWQR2QAZAgiC2WL1vZEg8TAJSshBcERMf5i6NsptX2zdfhmpxp4AgW\n"
    "V7xlnYGOQkbRO1ZSBcERBZzpLEz4vEPY7AJDsPiHp0qHkAPewpLuXAUSp4LaBhxZtfC8vN\n"
    "g79qB5amf+vlf7V9rDTasLEZE7l7yrJZ0+9sJf5OcL0TcTgzAR507YHRPwcYWtjwJUvOD4\n"
    "iJogA6ieGtF4fncgg61Mw1eRKuqwZZfU1gSCgEDeODeXx2yPASX+tZuogUukOATtjPPQ3y\n"
    "7OKbaUdJrpD0zAvQoTSraTrHVw9XV1eis+KrqtAAAAAwEAAQAAAQAkE4MK1Dn3AB6sEsGH\n"
    "2dYjXzEjc2xnZErXfd6ajs3Cg7zFJWf2mIKwdzIl5YbSnexztYMdbIX9vHfk3jml/njlRM\n"
    "zughJ5Ft1/7e+Nc5jyiSR0YIjbVMhEMZIXrncUivq9gSwkFzVhkRYxRYicW7tabeLGVhH2\n"
    "5184Sh339Qey9jw7LmSqN9JB2cr35hecwz/+Kwbgxe6lQ7zZln1Dbcu68h0sLXSbBsUIms\n"
    "SRvNh+o4Ji/R89lWQ+b4kv57TWRYcxg+ZDObGKBGDOnjRsUjiI/ovxHRjCF6EcDqApRyKI\n"
    "JHcxhYo8roarVpWsh5e5wDQnGhkyKQUDHh3t9GCRjWm/AAAAgEsuVjE/Np6K76ISBlonYT\n"
    "LvtpIPTIkM56xo4lQ7N97OmP4FLnoRHnM0mUpcQ8EQq7qtSum72KXBDIpfOBgCoa0NsnW5\n"
    "rehUrizMfpJollU4do/nJS4A3MOISG5T7AU/hRaAdQMecDt4yLV+/i3eKUqJr/g63WFSKv\n"
    "6Rl/43EJ0DAAAAgQDFYe7JQ5/ZVi/BMUS3x099lHroDLXVQI33ZRSUVu6yVL0xfMq2TlY/\n"
    "LEkLY5arLCjl6dHdc0TmiYiMI07U3NzEeu5Ezhj/0Hc/FWqo1FDgjXNEeMMYtqx4deyP/Q\n"
    "S53hPOZlNJnjhpoeb7a1GIGyOZymPJDPpR3Dv2V7wWPYeJxwAAAIEAuSrxFtvSfnmRYCbI\n"
    "TfGbLVvjucRygrQJUzrQ529y945AHjPSyFne/IfIzWuiwWVzh2+vNl5fQtstW5red67RmR\n"
    "OLssRFlE3ErxK+r4z1VwGQAUqXhwmADHSN2cKOqdb69BaiYCfuV7NwqVAyTjzGzZBuqAVY\n"
    "AXZE+ElKwPaut+sAAAAOY291bnQwQGJhcm9xdWUBAgMEBQ==\n"
    "-----END OPENSSH PRIVATE KEY-----\n"
    ,
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCOxOGDcJatXjjYAgDj+MPojfp9w2p/jwCPltpbhTvWQR2QAZAgiC2WL1vZEg8TAJSshBcERMf5i6NsptX2zdfhmpxp4AgWV7xlnYGOQkbRO1ZSBcERBZzpLEz4vEPY7AJDsPiHp0qHkAPewpLuXAUSp4LaBhxZtfC8vNg79qB5amf+vlf7V9rDTasLEZE7l7yrJZ0+9sJf5OcL0TcTgzAR507YHRPwcYWtjwJUvOD4iJogA6ieGtF4fncgg61Mw1eRKuqwZZfU1gSCgEDeODeXx2yPASX+tZuogUukOATtjPPQ3y7OKbaUdJrpD0zAvQoTSraTrHVw9XV1eis+Krqt count0@baroque\n"
    ,
    "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgYWlYMnJnCmdrdFNCcG9LVE0wTmlKZ2RO"
    "Uzg1MDRCc1dxekxDd1QyZXlCQlJCM2xRaHFmRmdQS05hQlVaaFBITmd6UzZzN2MKVHY3Vmt3MmdZ"
    "bmRwTG82T0FYSzlYMFdLVlV5TXIyRS9IeHBVelZpWkZQUEJVWXZUVXNZaER0djgzdzNNajV5LwpC"
    "b3VMU3RkT0dNMmlKME1pQjUveFUyWHlEZy9mL1V5a3QrZU9pTkZpQTErQmE0VU1SMHQ1Qlc0ZDVa"
    "b00wOExMCk9xUmdDclRmOVEyaG5QMUljMXBiVE9Lak9LNDB1aHpzM05kTHpudzJNZWpnUEQ1V3l6"
    "Y3JvbHZaT2tMOC9UTDYKRFRwQUNWSUNpOGRmeVdlQWxNTGRyTFQxNVo4THljQnVibTkreDFjK2dr"
    "Z1BvZEJXeXBHdHZ2RTFvR3IvQ2lKeQpUdVZKQ3EzU1JWS1A0V3BObFc5d0Z3Ci0tLSBDYUl0eUtm"
    "TTErVjY4US9uZkdkVFBvb2gzaEFOeHpMNmM2d0JpYnBqWHcwCkHzqtbExbH0cCFuhnPyxtpwYt0Y"
    "+07R4xI00OZ811XIvxPIQ8dwLakME9qISPIPH8tgd8Mjgb9yY8OF"
  },
  {"ed",
    "-----BEGIN OPENSSH PRIVATE KEY-----\n"
    "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\n"
    "QyNTUxOQAAACCUnC67IDwnZNFWZIjRzGbGFPfs1KbFB8/KdZeVJ9ghRgAAAJjRLja70S42\n"
    "uwAAAAtzc2gtZWQyNTUxOQAAACCUnC67IDwnZNFWZIjRzGbGFPfs1KbFB8/KdZeVJ9ghRg\n"
    "AAAECGvsfwfKj6rcbG98C5s/iK1KMx0lj5fX2hMVaJyfNz1pScLrsgPCdk0VZkiNHMZsYU\n"
    "9+zUpsUHz8p1l5Un2CFGAAAADmNvdW50MEBiYXJvcXVlAQIDBAUGBw==\n"
    "-----END OPENSSH PRIVATE KEY-----\n"
    ,
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJScLrsgPCdk0VZkiNHMZsYU9+zUpsUHz8p1l5Un2CFG count0@baroque\n"
    ,
    "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFHNFhrUSBUanhlR3p5M011MEhZ"
    "UklRUkZVaTB0aW5PRnBDcDdQOHVweFlrNUdFTTI0CjZub2FSUXdDNFpHVmh0azM0Ui9rRUVJd3E1"
    "QU81bjN6eEs1N2IzRGlzYk0KLS0tIGI2cXgrR0pZRmtCb0hWYUtqL3M2dnBLWGdxeXVva2J3QWxj"
    "dk9TazFvNDQKOE/jb2NU0Q1Q65HhyVaihlEBq6UOeyZumOjCXD4ztEL7bUOjDfkpITu1OTmkWJx+"
    "wJ5D/tdqU04paCw="
  },
};
