SELECT ''::zbitmap;
SELECT zbitmap_length('');
SELECT zbitmap_send('');
SELECT ','::zbitmap;
SELECT '-'::zbitmap;
SELECT '0'::zbitmap;
SELECT '0,'::zbitmap;
SELECT '0-'::zbitmap;
SELECT ',0'::zbitmap;
SELECT zbitmap_get(',0', 0);
SELECT zbitmap_get(',0', 1);
SELECT '-0'::zbitmap;
SELECT zbitmap_clr_range('', 0, 0);
SELECT zbitmap_set_range('', 0, 0);
SELECT zbitmap_set_range('', 0, 1);
SELECT zbitmap_set_range('', 1, 2);
SELECT zbitmap_set_range('0-1,3-4,6,8-', 60, 68);
SELECT zbitmap_send(zbitmap_set_range('0-1,3-4,6,8-', 60, 68));
SELECT zbitmap_xor(zbitmap_set_range('0-1,3-4,6,8-', 60, 68), '1-4');
SELECT ''::zbitmap = ''::zbitmap;
